smoketest connection with azure func app

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -53,13 +53,6 @@ jobs:
     needs: docker-build-push  # Ensures Docker image is built and pushed before deployment
 
     steps:
-    # - name: Lowercase the repo name and username
-    # run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
-    # - name: 'Login to Azure'
-    #   uses: azure/login@v1
-    #   with:
-    #     creds: ${{ secrets.SOAZURECREDENTIALS }}
-
     - name: 'Deploy to Azure Web App'
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v2
@@ -67,3 +60,18 @@ jobs:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.SOAZURECREDENTIALS }}
         images: 'shenolosman/vite-app-dockerize:dev'
+
+  # Job 4: Checks Smoke Test on Azure Function App 
+  smoke-test:
+    runs-on: ubuntu-latest
+    needs: deploy-to-azure
+
+    steps:
+    - name: Trigger Azure Function Smoke Test
+      run: |
+        RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" "https://shenol-functionapp.azurewebsites.net/")
+        if [ "$RESPONSE" -ne 200 ]; then
+          echo "Smoke test failed with status code $RESPONSE"
+          exit 1
+        fi
+  
